#!/usr/bin/env python3
"""Build app/opengraph-image.jpg — the link preview for WhatsApp/Instagram/Facebook.

Run by hand when the hero artwork or the lockup changes; it is deliberately not
wired into `npm run build`, the same way the Elementor exports in public/ are
regenerated by hand. The committed JPEG is the build output — this file exists
so that binary isn't the one unexplained artefact in the tree.

    python3 scripts/build-og-image.py

The composition is the hero as a guest first sees it: the ANIS and ZAFRAN
lockup over the sunflower field. A preview that matches the page it opens is
worth more than a prettier one that doesn't.

Requires Pillow (`pip3 install Pillow`). No other dependency, and nothing here
is macOS-specific — unlike build-icons.py, which needs a system font.
"""

from PIL import Image, ImageFilter

# 1.91:1, the ratio Facebook/WhatsApp lay their large card out for.
OUT_W, OUT_H = 1200, 630

SRC_BG = 'public/hero-sunflower-field.png'          # 1366x768
SRC_LOCKUP = 'public/wedding-lockup.png'           # 860x650, alpha
DST = 'app/opengraph-image.jpg'

# Scale applied to the lockup *after* trimming it to its ink. 0.80 lands it at
# 590px, 49% of the frame — deliberately bigger than the 33vw the live hero
# uses, because a WhatsApp bubble renders this card at roughly 200-330px and
# the type has to survive that downscale. 590 < 630 also means the whole
# lockup survives a 1:1 centre crop, which some clients apply to thumbnails.
LOCKUP_SCALE = 0.80

# Nudge up from true centre: the two caption lines at the bottom of the lockup
# are visually lighter than the names, so geometric centre reads low. Taste.
OPTICAL_LIFT = 8

# A cream scrim behind the type, 0-255. Left at 0 on purpose: measured
# background luminance under the lockup runs 194-222 (sd ~20, i.e. not busy)
# against ink at 59, so the contrast is already there and a veil would only
# mute the artwork. It's the same pairing the live hero already proves. Raise
# this if the preview ever reads noisy in a real chat bubble.
VEIL_ALPHA = 0

# Mirrors HeroSection.tsx's drop-shadow(0 2px 10px rgba(0,0,0,0.15)) so the
# preview and the page it opens look continuous. CSS blur-radius 10 ~= sigma 5.
SHADOW_OFFSET = (0, 2)
SHADOW_BLUR = 5
SHADOW_ALPHA = 0.15

# 4:4:4 (subsampling=0), not the usual 4:2:0: the sage-green "and" sits against
# near-white and the condensed-serif strokes are thin, and chroma subsampling
# smears both. Baseline rather than progressive — progressive saves ~7KB here
# and a handful of older link scrapers mishandle it, which is a bad trade on
# the one asset whose whole job is being scraped.
QUALITY = 86


def main():
    bg = Image.open(SRC_BG).convert('RGB')

    # The source is 1.779:1 and we need 1.905:1, so the crop is
    # height-constrained: 1366/1.905 = 717px, leaving only 51px of slack in the
    # whole frame. Anchoring to the bottom spends all of it on flat gradient
    # sky rather than on the large foreground sunflowers, which carry the
    # character and are already cut off by the frame. It also lifts the horizon
    # from 47% to 40% of the output height, nearer the upper third.
    crop_h = round(bg.width * OUT_H / OUT_W)
    bg = bg.crop((0, bg.height - crop_h, bg.width, bg.height))
    bg = bg.resize((OUT_W, OUT_H), Image.LANCZOS)

    # Trim to the alpha bbox first — the PNG carries ~60px of empty padding a
    # side, so compositing it as-authored would leave the mark looking
    # undersized and optically off-centre.
    lockup = Image.open(SRC_LOCKUP).convert('RGBA')
    lockup = lockup.crop(lockup.getbbox())
    lw = round(lockup.width * LOCKUP_SCALE)
    lh = round(lockup.height * LOCKUP_SCALE)
    lockup = lockup.resize((lw, lh), Image.LANCZOS)

    x = (OUT_W - lw) // 2
    y = (OUT_H - lh) // 2 - OPTICAL_LIFT

    canvas = bg.convert('RGBA')

    if VEIL_ALPHA:
        veil = Image.new('RGBA', (OUT_W, OUT_H), (240, 232, 220, VEIL_ALPHA))
        canvas = Image.alpha_composite(canvas, veil)

    # Shadow: a black layer stencilled by the lockup's own alpha, blurred and
    # faded, laid down before the lockup itself.
    shadow = Image.new('RGBA', (OUT_W, OUT_H), (0, 0, 0, 0))
    stencil = Image.new('RGBA', (lw, lh), (0, 0, 0, 255))
    stencil.putalpha(lockup.getchannel('A'))
    shadow.paste(stencil, (x + SHADOW_OFFSET[0], y + SHADOW_OFFSET[1]))
    shadow = shadow.filter(ImageFilter.GaussianBlur(SHADOW_BLUR))
    shadow.putalpha(shadow.getchannel('A').point(lambda a: round(a * SHADOW_ALPHA)))
    canvas = Image.alpha_composite(canvas, shadow)

    layer = Image.new('RGBA', (OUT_W, OUT_H), (0, 0, 0, 0))
    layer.paste(lockup, (x, y))
    canvas = Image.alpha_composite(canvas, layer)

    canvas.convert('RGB').save(
        DST, 'JPEG', quality=QUALITY, subsampling=0, optimize=True, progressive=False
    )
    print(f'{DST}: {OUT_W}x{OUT_H}, lockup {lw}x{lh} at ({x}, {y})')


if __name__ == '__main__':
    main()
